/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musicRecord;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.Point;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JComboBox;
import java.awt.event.FocusEvent;


/**
 *
 * discName
   artistName
   discType
   releaseDate
   numberOfSongs
   price
   stock
 * @author chris
 */
public class MusicRecordFrame extends javax.swing.JFrame {
    private final Dimension SCREEN_SIZE = Toolkit.getDefaultToolkit().getScreenSize();
    private final Dimension FRAME_SIZE = new Dimension(600,450);
    private final String[] listDiscType = {"","Single", "EP", "Álbum", "Recopilación", "Live"};
    private final Date firstAlbumReleaseDate = new Date(1889,1,1,1,1,11);
    private String discName;
    private String artistName;
    private String discType;
    private LocalDate releaseDate;
    private int numberOfSongs;
    private int price;
    private int stock;
    private final int[] listKeyCount = {0,0,0,0,0};
    
    /**
     * Creates new form MusicRecordFrame
     */
    public MusicRecordFrame() {

        initComponents();
        setDefaultTextWarning();
    }
    
    
    
    private Point getScreenCenter(){
        final int WIDTH_CENTER = (int)((SCREEN_SIZE.getWidth() - FRAME_SIZE.getWidth())/2);
        final int HEIGHT_CENTER = (int)((SCREEN_SIZE.getHeight() - FRAME_SIZE.getHeight())/2);
        final Point SCREEN_CENTER = new Point(WIDTH_CENTER, HEIGHT_CENTER);
        System.out.println("Se definió el centro de la pantalla");
        return SCREEN_CENTER;
    }
    private boolean validString(String text){
        if(text.isEmpty() || text.trim().isEmpty()){
            return false;
        }else{
            return true;
        }
    }
    
    private boolean validInt(int number){
        final int MAX_INT_VALUE = 2147483647;
        if(number<= 0 || number >= MAX_INT_VALUE){
            return false;
        }else{
            return true;
        }
    }
    
    private void setDefaultTextWarning(){
        discNameWarningLabel.setText("");
        artistNameWarningLabel.setText("");
        numberOfSongsWarningLabel.setText("");
        discTypeWarningLabel.setText("");
        releaseDateWarningLabel.setText("");
        priceWarningLabel.setText("");
        stockWarningLabel.setText("");
        System.out.println("Se definió las advertencias en blanco");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        musicRecordPanel = new javax.swing.JPanel();
        discLabel = new javax.swing.JLabel();
        discNameTextField = new javax.swing.JTextField();
        discNameWarningLabel = new javax.swing.JLabel();
        artistLabel = new javax.swing.JLabel();
        artistNameTextField = new javax.swing.JTextField();
        artistNameWarningLabel = new javax.swing.JLabel();
        releaseDateLabel = new javax.swing.JLabel();
        numberOfSongsLabel = new javax.swing.JLabel();
        numberOfSongsTextField = new javax.swing.JTextField();
        numberOfSongsWarningLabel = new javax.swing.JLabel();
        discTypeLabel = new javax.swing.JLabel();
        discTypeComboBox = new JComboBox<>(listDiscType);
        discTypeWarningLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        priceWarningLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        stockTextField = new javax.swing.JTextField();
        stockWarningLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        registerButton = new javax.swing.JButton();
        cleanFieldsButton = new javax.swing.JButton();
        releaseDateWarningLabel = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        findDataEditMenu = new javax.swing.JMenu();
        editFindByDiscMenu = new javax.swing.JMenuItem();
        editFindByArtistMenu = new javax.swing.JMenuItem();
        editFindByDiscTypeMenu = new javax.swing.JMenuItem();
        editFindByCustomMenu = new javax.swing.JMenuItem();
        deleteMenu = new javax.swing.JMenu();
        findDataDeleteMenu = new javax.swing.JMenu();
        deleteFindByDiscMenu = new javax.swing.JMenuItem();
        deleteFindByArtistMenu = new javax.swing.JMenuItem();
        deleteFindByDiscTypeMenu = new javax.swing.JMenuItem();
        deleteFindByCustomMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de discos");
        setLocation(getScreenCenter());
        setMaximumSize(SCREEN_SIZE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        setName("musicRecordFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(620, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(620, 420));

        musicRecordPanel.setMaximumSize(new java.awt.Dimension(3276, 3276));

        discLabel.setText("Disco");
        discLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        discNameTextField.setToolTipText("Ingrese el nombre del disco");
        discNameTextField.setMaximumSize(new java.awt.Dimension(2147, 21474));
        discNameTextField.setPreferredSize(new java.awt.Dimension(200, 22));
        discNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                discNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                discNameTextFieldFocusLost(evt);
            }
        });
        discNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discNameTextFieldKeyTyped(evt);
            }
        });

        discNameWarningLabel.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        discNameWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        discNameWarningLabel.setText("Error");

        artistLabel.setText("Artista");

        artistNameTextField.setToolTipText("Ingrese el nombre del artista");
        artistNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                artistNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                artistNameTextFieldFocusLost(evt);
            }
        });
        artistNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                artistNameTextFieldKeyTyped(evt);
            }
        });

        artistNameWarningLabel.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        artistNameWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        artistNameWarningLabel.setText("Error");

        releaseDateLabel.setText("Fecha de lanzamiento");

        numberOfSongsLabel.setText("N° de canciones");

        numberOfSongsTextField.setToolTipText("Ingrese el numero de canciones");
        numberOfSongsTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberOfSongsTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberOfSongsTextFieldFocusLost(evt);
            }
        });
        numberOfSongsTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberOfSongsTextFieldKeyTyped(evt);
            }
        });

        numberOfSongsWarningLabel.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        numberOfSongsWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        numberOfSongsWarningLabel.setText("Error");

        discTypeLabel.setText("Tipo de disco");

        discTypeComboBox.setToolTipText("Escoja el tipo de disco");
        discTypeComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                discTypeComboBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                discTypeComboBoxFocusLost(evt);
            }
        });
        discTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discTypeComboBoxActionPerformed(evt);
            }
        });

        discTypeWarningLabel.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        discTypeWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        discTypeWarningLabel.setText("Error");

        priceLabel.setText("Precio");

        priceTextField.setToolTipText("Ingrese el precio del disco");
        priceTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                priceTextFieldFocusLost(evt);
            }
        });
        priceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTextFieldKeyTyped(evt);
            }
        });

        priceWarningLabel.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        priceWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        priceWarningLabel.setText("Error");

        stockLabel.setText("Stock");

        stockTextField.setToolTipText("Ingrese las unidades existentes del disco");
        stockTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                stockTextFieldFocusLost(evt);
            }
        });
        stockTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockTextFieldKeyTyped(evt);
            }
        });

        stockWarningLabel.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        stockWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        stockWarningLabel.setText("Error");

        registerButton.setText("Registrar");

        cleanFieldsButton.setText("Limpiar");

        releaseDateWarningLabel.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        releaseDateWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        releaseDateWarningLabel.setText("Error");

        javax.swing.GroupLayout musicRecordPanelLayout = new javax.swing.GroupLayout(musicRecordPanel);
        musicRecordPanel.setLayout(musicRecordPanelLayout);
        musicRecordPanelLayout.setHorizontalGroup(
            musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicRecordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numberOfSongsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(discLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(artistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(discTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(artistNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(discNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberOfSongsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(discTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(musicRecordPanelLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(discTypeWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(priceWarningLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stockWarningLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(artistNameWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(discNameWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(numberOfSongsWarningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(releaseDateLabel)
                    .addGroup(musicRecordPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(releaseDateWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(musicRecordPanelLayout.createSequentialGroup()
                                    .addComponent(cleanFieldsButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(registerButton))
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        musicRecordPanelLayout.setVerticalGroup(
            musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicRecordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(discLabel)
                        .addComponent(releaseDateLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(discNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musicRecordPanelLayout.createSequentialGroup()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(releaseDateWarningLabel))
                    .addGroup(musicRecordPanelLayout.createSequentialGroup()
                        .addComponent(discNameWarningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(artistLabel)
                            .addComponent(artistNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(artistNameWarningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfSongsLabel)
                            .addComponent(numberOfSongsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfSongsWarningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discTypeLabel)
                            .addComponent(discTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discTypeWarningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceWarningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockLabel)
                            .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockWarningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(musicRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(cleanFieldsButton))
                .addGap(15, 15, 15))
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        fileMenu.setText("Archivo");
        jMenuBar1.add(fileMenu);

        EditMenu.setText("Editar");

        findDataEditMenu.setText("Buscar por");

        editFindByDiscMenu.setText("Nombre del disco");
        findDataEditMenu.add(editFindByDiscMenu);

        editFindByArtistMenu.setText("Nombre del artista");
        findDataEditMenu.add(editFindByArtistMenu);

        editFindByDiscTypeMenu.setText("Tipo de disco");
        findDataEditMenu.add(editFindByDiscTypeMenu);

        editFindByCustomMenu.setText("Personalizado");
        findDataEditMenu.add(editFindByCustomMenu);

        EditMenu.add(findDataEditMenu);

        jMenuBar1.add(EditMenu);

        deleteMenu.setText("Eliminar");

        findDataDeleteMenu.setText("Buscar por");

        deleteFindByDiscMenu.setText("Nombre del disco");
        findDataDeleteMenu.add(deleteFindByDiscMenu);

        deleteFindByArtistMenu.setText("Nombre del artista");
        findDataDeleteMenu.add(deleteFindByArtistMenu);

        deleteFindByDiscTypeMenu.setText("Tipo de disco");
        findDataDeleteMenu.add(deleteFindByDiscTypeMenu);

        deleteFindByCustomMenu.setText("Personalizado");
        findDataDeleteMenu.add(deleteFindByCustomMenu);

        deleteMenu.add(findDataDeleteMenu);

        jMenuBar1.add(deleteMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musicRecordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musicRecordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void discTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discTypeComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_discTypeComboBoxActionPerformed

    private void discNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discNameTextFieldFocusLost
        // TODO add your handling code here:
        String discNameText = discNameTextField.getText();
        if(!validString(discNameText)){
            discNameWarningLabel.setText("Este campo es obligatorio ");
        }
    }//GEN-LAST:event_discNameTextFieldFocusLost

    private void discNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discNameTextFieldFocusGained
        // TODO add your handling code here:
        discNameWarningLabel.setText("");
    }//GEN-LAST:event_discNameTextFieldFocusGained

    private void artistNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_artistNameTextFieldFocusLost
        // TODO add your handling code here:
        String artistNameText = artistNameTextField.getText();
        if(!validString(artistNameText)){
            artistNameWarningLabel.setText("Este campo es obligatorio");
        }
    }//GEN-LAST:event_artistNameTextFieldFocusLost

    private void artistNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_artistNameTextFieldFocusGained
        // TODO add your handling code here:
        artistNameWarningLabel.setText("");
    }//GEN-LAST:event_artistNameTextFieldFocusGained

    private void numberOfSongsTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberOfSongsTextFieldFocusLost
        // TODO add your handling code here:
        String numberOfSongsText = numberOfSongsTextField.getText();
        if(!validString(numberOfSongsText)){
            numberOfSongsWarningLabel.setText("Este campo es obligatorio");
        }else{
            int numberOfSongsData = Integer.parseInt(numberOfSongsTextField.getText());
            if(!validInt(numberOfSongsData)){
                numberOfSongsWarningLabel.setText("Este campo es obligatorio");
            }    
        }
    }//GEN-LAST:event_numberOfSongsTextFieldFocusLost

    private void numberOfSongsTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberOfSongsTextFieldFocusGained
        // TODO add your handling code here:
        numberOfSongsWarningLabel.setText("");
    }//GEN-LAST:event_numberOfSongsTextFieldFocusGained

    private void discTypeComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discTypeComboBoxFocusLost
        // TODO add your handling code here:
        int listDiscTypeIndex = discTypeComboBox.getSelectedIndex();
        if(!validInt(listDiscTypeIndex)){
            discTypeWarningLabel.setText("Este campo es obligatorio");
        }  
    }//GEN-LAST:event_discTypeComboBoxFocusLost

    private void discTypeComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discTypeComboBoxFocusGained
        // TODO add your handling code here:
        discTypeWarningLabel.setText("");
    }//GEN-LAST:event_discTypeComboBoxFocusGained

    private void priceTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceTextFieldFocusLost
        // TODO add your handling code here:
        String priceText = priceTextField.getText();
        if(!validString(priceText)){
            priceWarningLabel.setText("Este campo es obligatorio");
        }else{
            int priceData = Integer.parseInt(priceTextField.getText());
            if(!validInt(priceData)){
                priceWarningLabel.setText("El dato ingresado no es permitido");
            }    
        }
    }//GEN-LAST:event_priceTextFieldFocusLost

    private void priceTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceTextFieldFocusGained
        // TODO add your handling code here:
        priceWarningLabel.setText("");
    }//GEN-LAST:event_priceTextFieldFocusGained

    private void stockTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stockTextFieldFocusLost
        // TODO add your handling code here:
        String stockText = priceTextField.getText();
        if(!validString(stockText)){
            stockWarningLabel.setText("Este campo es obligatorio");
        }else{
            int stockData = Integer.parseInt(stockTextField.getText());
            if(!validInt(stockData)){
                stockWarningLabel.setText("El dato ingresado no es permitido");
            }    
        }
        
    }//GEN-LAST:event_stockTextFieldFocusLost

    private void discNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discNameTextFieldKeyTyped
        // TODO add your handling code here:
        listKeyCount[0] ++;
        char c = evt.getKeyChar();
        boolean backSpacePressed = c == KeyEvent.VK_BACK_SPACE;
        boolean deletePressed = c == KeyEvent.VK_DELETE;
        if(listKeyCount[0] == 50 || discNameTextField.getText().length() >= 50){
            evt.consume();
            discNameWarningLabel.setText("No puedes ingresar mas de 50 caracteres");
        }
        if(backSpacePressed || deletePressed){
            listKeyCount[0] = discNameTextField.getText().length();
            discNameWarningLabel.setText("");
            discNameTextFieldKeyTyped(evt);
        }
    }//GEN-LAST:event_discNameTextFieldKeyTyped

    private void numberOfSongsTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberOfSongsTextFieldKeyTyped
        // TODO add your handling code here:
        prohibitedNoNumerics(evt);
    }//GEN-LAST:event_numberOfSongsTextFieldKeyTyped

    private void priceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextFieldKeyTyped
        // TODO add your handling code here:
        prohibitedNoNumerics(evt);
    }//GEN-LAST:event_priceTextFieldKeyTyped

    private void stockTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockTextFieldKeyTyped
        // TODO add your handling code here:
        prohibitedNoNumerics(evt);
    }//GEN-LAST:event_stockTextFieldKeyTyped

    private void artistNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_artistNameTextFieldKeyTyped
        // TODO add your handling code here:
        listKeyCount[1] ++;
        char c = evt.getKeyChar();
        boolean backSpacePressed = c == KeyEvent.VK_BACK_SPACE;
        boolean deletePressed = c == KeyEvent.VK_DELETE;
        if(listKeyCount[1] >= 50){
            evt.consume();
            artistNameWarningLabel.setText("No puedes ingresar mas de 50 caracteres");
        }
        if(backSpacePressed || deletePressed){
            listKeyCount[1] = artistNameTextField.getText().length();
            artistNameWarningLabel.setText("");
        }
        
    }//GEN-LAST:event_artistNameTextFieldKeyTyped
    
    
    
    
    private void prohibitedNoNumerics(KeyEvent evt){
        char c = evt.getKeyChar();
        boolean nonEssentialKeys = c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && c != KeyEvent.VK_TAB;
        if (!Character.isDigit(c) && nonEssentialKeys) {
            evt.consume();
            print("Prohibí no-numericos donde estos no corresponde");
        }
                
    }
    
    
    private void print(String text){
        System.out.println(text);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MusicRecordFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EditMenu;
    private javax.swing.JLabel artistLabel;
    private javax.swing.JTextField artistNameTextField;
    private javax.swing.JLabel artistNameWarningLabel;
    private javax.swing.JButton cleanFieldsButton;
    private javax.swing.JMenuItem deleteFindByArtistMenu;
    private javax.swing.JMenuItem deleteFindByCustomMenu;
    private javax.swing.JMenuItem deleteFindByDiscMenu;
    private javax.swing.JMenuItem deleteFindByDiscTypeMenu;
    private javax.swing.JMenu deleteMenu;
    private javax.swing.JLabel discLabel;
    private javax.swing.JTextField discNameTextField;
    private javax.swing.JLabel discNameWarningLabel;
    private javax.swing.JComboBox<String> discTypeComboBox;
    private javax.swing.JLabel discTypeLabel;
    private javax.swing.JLabel discTypeWarningLabel;
    private javax.swing.JMenuItem editFindByArtistMenu;
    private javax.swing.JMenuItem editFindByCustomMenu;
    private javax.swing.JMenuItem editFindByDiscMenu;
    private javax.swing.JMenuItem editFindByDiscTypeMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu findDataDeleteMenu;
    private javax.swing.JMenu findDataEditMenu;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel musicRecordPanel;
    private javax.swing.JLabel numberOfSongsLabel;
    private javax.swing.JTextField numberOfSongsTextField;
    private javax.swing.JLabel numberOfSongsWarningLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel priceWarningLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel releaseDateLabel;
    private javax.swing.JLabel releaseDateWarningLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JTextField stockTextField;
    private javax.swing.JLabel stockWarningLabel;
    // End of variables declaration//GEN-END:variables
}
